# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  auto_ids: true

# Permalinks
permalink:        pretty

# Server
source:           docs
destination:      _gh_pages
port:             9002
baseurl:          ""
url:              https://bootsblogger.github.io
encoding:         UTF-8

gems:
  - jekyll-redirect-from
  - jekyll-sitemap

# Social
title: Bootsblogger
description: Blogger + Bootstrap + <3
authors: Igoy Nawamreh
social_logo_path: /assets/brand/bootstrap-social-logo.png
social_image_path: /assets/brand/bootstrap-social.png

# Custom variables
current_version:   1.0.0-alpha.1
bootstrap_version: 4.0.0-alpha.6
repo:              https://github.com/bootsblogger/bootsblogger

download:
  source:         "https://github.com/bootsblogger/bootsblogger/archive/v1.0.0-beta.zip"
  dist:           "https://github.com/bootsblogger/bootsblogger/releases/download/v1.0.0-beta/bootsblogger-1.0.0-beta-dist.zip"

demo:             https://bootsblogger-demo.blogspot.com
blog:             https://bootsblogger-blog.blogspot.com
expo:             https://bootsblogger-expo.blogspot.com
themes:           https://bootsblogger-themes.blogspot.com
